"""empty message

Revision ID: 2658b28d7394
Revises: c2be6870b441
Create Date: 2017-04-18 22:39:33.326478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2658b28d7394'
down_revision = 'c2be6870b441'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classifiers', sa.Column('test_info', sa.String(length=550), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('classifiers', 'test_info')
    # ### end Alembic commands ###
