"""empty message

Revision ID: 5b97257de979
Revises: 
Create Date: 2017-04-14 23:18:44.061293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b97257de979'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classifiers', sa.Column('image_id', sa.String(length=250), nullable=True))
    op.add_column('classifiers', sa.Column('task_id', sa.String(length=250), nullable=True))
    op.add_column('classifiers', sa.Column('training_label_name_file_path', sa.String(length=550), nullable=True))
    op.drop_index('ix_classifiers_name', table_name='classifiers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_classifiers_name', 'classifiers', ['name'], unique=False)
    op.drop_column('classifiers', 'training_label_name_file_path')
    op.drop_column('classifiers', 'task_id')
    op.drop_column('classifiers', 'image_id')
    # ### end Alembic commands ###
