"""empty message

Revision ID: 64320c3534e7
Revises: 2658b28d7394
Create Date: 2017-04-18 22:40:26.839337

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '64320c3534e7'
down_revision = '2658b28d7394'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('classifiers', 'test_info')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classifiers', sa.Column('test_info', mysql.VARCHAR(length=550), nullable=True))
    # ### end Alembic commands ###
