"""empty message

Revision ID: c26dbd3acb65
Revises: 20d519aa1034
Create Date: 2017-04-17 15:48:10.942059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c26dbd3acb65'
down_revision = '20d519aa1034'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classifiers', sa.Column('labels', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('classifiers', 'labels')
    # ### end Alembic commands ###
