"""empty message

Revision ID: c2be6870b441
Revises: e8dbc95d62f1
Create Date: 2017-04-17 18:52:01.035312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2be6870b441'
down_revision = 'e8dbc95d62f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_status_records', sa.Column('update_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_status_records', 'update_time')
    # ### end Alembic commands ###
