"""empty message

Revision ID: dbf8b1c7392c
Revises: 64320c3534e7
Create Date: 2017-04-19 14:42:34.204301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbf8b1c7392c'
down_revision = '64320c3534e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classifiers', sa.Column('task_type', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('classifiers', 'task_type')
    # ### end Alembic commands ###
