"""empty message

Revision ID: e8dbc95d62f1
Revises: 7d27b4169945
Create Date: 2017-04-17 16:06:27.724877

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e8dbc95d62f1'
down_revision = '7d27b4169945'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('test', mysql.VARCHAR(length=250), nullable=True))
    # ### end Alembic commands ###
